### PR TITLE
add simple noscript message

### PR DESCRIPTION
**Pull request by sashahart**
per #76

### CODE REVIEW

**Comment by wilsaj** [comment]
Maybe also link to http://enable-javascript.com/ ?

**Comment by sashahart** [comment]
If this changeset fulfills the requirement as originally/sparsely specified, and doesn't break anything, I'd like to merge it as-is and close the existing ticket. If you want to after that make further changes, doesn't matter to me. And I'd be just as happy if you provided a complete alternative PR, as long as the ticket gets closed. Any further requirements could be new issues. In short, whatever

**Comment by wilsaj** [comment]
Sorry for underspecifying - at the time it was more of a note-to-self.

I don't mind merging as is, but I'd also like to include some conditional text for IE < 11 before closing the original issue. The app might work for IE 10 but we don't really have time for deprecated browsers.

**Comment by sashahart** [comment]
This PR is totally trivial, my suggestion is that we close this and you do a different one to your specs. And I'll poke at it so we can pretend we have a code review process, but almost certainly I'll just +1 LGTM immediately.

**Comment by wilsaj** [comment]
sounds good

**Pull request merged**
