### PR TITLE
prototype disclaimer

### PR DESCRIPTION
**Pull request by sashahart**
Here is a prototype of the disclaimer dialog. 

For now it is appearing at every load, for the purposes of testing/feedback. 

Later on we can check and set a flag in localstorage to indicate whether the user has dismissed the popup before.

This "looks good to me" on Chrome and Firefox but there are no tests, caveat emptor.

Even if we get this change nailed down to where we want it, it can't be deployed unless someone knows how to deploy the frontend... and I'd say we should do some kind of QA in a test environment before deploying all these changes.

### CODE REVIEW

**Comment by wilsaj** [comment]
Looks alright to me, though I think it's weird and unfriendly to greet first-time users with a legal wall of text that is most likely going to be dismissed without being read. I'd prefer a prominent-enough button or link somewhere that opens this dialog.

In either case, can you add `dialog-polyfill` to the package.json and commit that?

`npm install --save dialog-polyfill` should add it.

**Comment by christoball** [comment]
I have some color suggestions.

For the main legal text, I think this should be a black. Looks like it has a rgba value that includes a .54 transparency.

And for the button, I think it should match the $darker-blue variable, #2c88a9.

Richard just left the office to go on vacay for a week, but from my understanding, the pop-up at the beginning seemed to be the preferred way that legal wanted it to happen. I think that pushing this now will take a lot of pressure off things. If there is a strong desire to change the behavior, then we can make that happen later if we like.

**Comment by sashahart** [comment]
Sure, if it is an option just to not have a required disclaimer modal, it's less work for us and a LOT less friction for users. Modals aren't really supposed to have this much text in them. If this is intended to have the force of ToS then I have doubts whether it is enforceable, but what do I know. Even just implementing this as a separate page is less fragile at a technical level and matches what sites usually do with ToS ... but I understand this an edict from above, so whatever.

At any rate, dismissing the popup at every page load is an exceptionally brutal amount of friction for users (hit F5 for updates? Ooops) and I sort of doubt it was the intention. I just wanted to hash out the design of this thing first (it took me way too long to account for how it works on smaller screens, play with that if you get a chance).

This is using the default styling and colors from our MDL dependencies. I'm not attached to those, but my personal opinion is that if we are making it an absolute requirement to press a button in order to use the app, that button should not fade into the background, even though that cyan color is more aesthetically harmonized or whatever. Anyway, I'll merge whatever color you decide, so let me know if you want any help figuring out the CSS for that.

**Comment by christoball** [comment]
@sashahart Agreed the cyan is a little less prominent. My alternative would be a dark grey, i.e. #333333

**Comment by mpavon66** [comment]
@wilsaj Andy:
Congratulations on your new role as paternal figure. I just made it back from vacation, first day at work. Chris showed me a local-development version of the disclaimer in the viewer and it looks good. It would be fantastic if at a break in between your paternal duties you could push the legal disclaimer to be available for the users. TWDB Exec at a meeting with Felicia today  was asking about the disclaimer and its status.

**Comment by wilsaj** [comment]
@sashahart and @christoball are you ok with merging and deploying this as is?

**Comment by christoball** [comment]
@wilsaj If it's not too much trouble, changing the button to a darkgrey, and also on hover, would be preferable, but I understand if you just want to push it out to make it easier.

**Comment by wilsaj** [comment]
I'm not sure if we can directly push to this PR since it's in a private fork, so any changes from me or you would need to be done as separate PR.

I think the biggest question here is whether or not we want to wait for way of semi-permanently dismissing this popup (via cookie or local storage), or if we are okay with the heavy-handed approach of this dialog popping up every time on every page load.

**Comment by mpavon66** [comment]
I believe a semi-permanent dismissal of this popup (via cookie or local storage) is preferable if it can be accomplished within the next couple of days.

**Comment by christoball** [comment]
@geochik has said now we have a direct message from the acting EA, Amanda Lavin, that actually, it should pop up every time the page is loaded. 

So, it seems like there's no need to develop a cookie, etc and it should be pushed as is. 

@wilsaj can you go ahead deploy as is to resolve this asap?

**Comment by sashahart** [comment]
OK, we can work out whatever details you want later

**Comment by wilsaj** [comment]
deployed

**Comment by geochik** [comment]
Thank you so much Andy.

@christoball There are some weird characters in the disclaimer text when I bring it up on my iPhone. Can that be remedied?[image1.PNG]

Sent from my iPhone

On Jun 22, 2016, at 5:04 PM, Andy Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:


deployed

-

**Comment by sashahart** [comment]
@christoball: would you mind doing a PR with the #333333?

**Comment by christoball** [comment]
@sashahart I don't mind, but is it ok if I edit the material.css file to do that until I get the MDL library set up? @wilsaj ?

**Comment by wilsaj** [comment]
My thoughts: The tradeoff for the separate MDL fork is that the MDL source is easier to navigate and track changes, but it has the cost of a separate build step and some time spent wrestling with node tools to get that build step working. If that cost outweighs the benefit, then drop it.

This goes for pretty much everything on this project. Most decisions were made hastily and based on convenience in order to meet an absurdly tight deadline. Now that the deadline is no longer steering the ship, it's a fine time to re-evaluate and come up with less terrible solutions. I'm trying to limit my involvement in these discussions since I don't have much time for them and my opinions on things like tooling shouldn't matter since I'll be completely out of the picture real soon.

**Pull request merged**
