### PR TITLE
updated planning_bg image, palette fixes

### PR DESCRIPTION
**Pull request by christoball**
I fixed the planning_bg image to better match the palette.

I also adjusted the color variables slightly.

Left aligned twdb logo pending legal disclaimer language.

Additionally, I changed the 'expand drawer' button to a right chevron, signalling that the control panel slides open right to fit expected behavior.

@wilsaj @sashahart Does this all seem alright?

### CODE REVIEW

**Comment by sashahart** [comment]
Reading the code itself, I don't see how it would affect anything functionally. It also doesn't seem to affect anything functionally when run locally on Chrome (things are wonky in Firefox, but that isn't due to this patch). So technically it looks good to me.

Aesthetic and UX choices aren't really my department but for what it's worth, I think these are improvements. I don't understand about the logo alignment but that doesn't matter to me.

One trivially tiny detail: it would be nice if you could remove the .DS_Store files, just to keep things tidy. If this isn't old news to you, you can force push to your branch to update this same PR. Worst case, I can do another commit to remove them later. You can have git ignore them systemwide by putting `.DS_Store` in your `~/.gitignore`

**Comment by sashahart** [comment]
I fiddled the .DS_Store stuff, rebased and pushed this back up so IMO it's ready to merge. Unless  I hear something to the contrary, I'll wait until tomorrow to merge in case discussion might be wanted, since we're still feeling out project tempo here I think

**Comment by wilsaj** [comment]
Oh hey, one thing - we have a fork of the material-design-lite library https://github.com/TNRIS/material-design-lite that is intended to track changes to vendor'd MDL files like `material.js`. It requires a little more setup, but advantages of the fork are:
- code is laid out pre-build step to it is a bit easier to navigate (rather than huge output compiled files)
- father reaching changes are easier to implement you can use their build system (like changing to our custom drawer width)
- you can track upstream issues and changesets

**Comment by sashahart** [comment]
That's good information. Since we are vendoring files that should be changed upstream somewhere, we need to document which vendored files should be changed at which upstream locations, and document or automate the process of copying those files from those upstreams to update this repo.

I'll just merge something if it doesn't look broken - although I'd be happy enough for TNRIS to formally mark someone other than me as the gatekeeper!

I wonder if this wouldn't work a little more clearly if MDL were kept as a submodule, then it wouldn't even be possible to edit a vendored file to put it out of sync with upstream (in this case with the TNRIS fork of MDL).

I'm disappointed that we can't override the chevron in CSS. My first preference would be not to depend on a fork of MDL at all, but just layer our styles on top of a pinned version of MDL and then move that version around (to manage breakage in our app due to churn in upstream MDL). Less maintenance complexity and one less build task

**Comment by wilsaj** [comment]
I agree with all of those points. I'm not proud of how much technical debt this project has racked up in its short lifetime but I'll try to point it out where I know it to exist.

MDL is the only vendor'd library that has been adulterated, and the changes that needed to be made came in at last minute so it was done pretty fast-and-loose. The fork was just the fastest way to get it done, not necessarily the most maintainable. The process I used was to run the MDL build and copy all the dist files to `vendor/`.

Last I checked, MDL devs were focusing on a 2.0 release that would be more modular and easier to do this sort of thing, but as it's written the 1.x release requires editing the javascript.

**Pull request merged**
